#!/bin/sh
set -e

chown -R photon:photon /var/db/photon

BOOTSTRAPPED="/var/db/photon/.bootstrapped"

if [ ! -e $BOOTSTRAPPED ]; then
	gosu photon java -jar /usr/local/share/photon/photon.jar \
		-data-dir /var/db/photon \
		-nominatim-import -host ${PGHOST} -user ${PGUSER} \
		-languages ${PHOTON_LANGUAGES}

	touch $BOOTSTRAPPED
fi

gosu photon java -jar /usr/local/share/photon/photon.jar -data-dir /var/db/photon